### ISSUE TITLE
Example to rotate triangle from 0 to 90 degrees

### ISSUE THREAD

**Issue by maheshpj** [maheshpj/Learn-Opengl#2]

**Comment by maheshpj** [comment]
Added triangle rotation 0 to 90 degrees example

**Comment by dmsurti** [comment]
```
 float speed = -1.0f;
 double deg = 0.0f;
```
Then, you immediately have:

```
if(deg == 0.0f || deg == 90.0f) {
    speed = -speed;
    usleep(1000000);
}
```

 * You are inverting speed at the very first run of the frame update loop. You might as well start with `speed = 1.0f`. 

* There is no need to do deg to rad conversion as `0 to 90 deg` is `0 to 1.57`, so incrementing every time by say `10 degrees (0.17)` will work. Then you don't even need deg, rad variables and every loop `angle = elapsed_seconds + angle` will update the angle. 

* `if(deg == 0.0f || deg == 90.0f) {` is better handled as `if(deg < 0.0f || deg > 90.0f) {`, think precision!

* IMHO, No need for `usleep`, but it's OK to have now that you have added it.

**Comment by maheshpj** [comment]
@dmsurti PR is updated with recent review comment changes
